apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: kubernetes-el-demo
type: Opaque
stringData:
  username: "demo-user"
  password: "not-a-real-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: large-secret
  namespace: kubernetes-el-demo
type: Opaque
stringData:
  api-token: "sk_test_0123456789abcdef0123456789abcdef"
  ssh-key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    NOT-A-REAL-KEY-JUST-DEMO-CONTENT-FOR-KUBERNETES-EL
    NOT-A-REAL-KEY-JUST-DEMO-CONTENT-FOR-KUBERNETES-EL
    NOT-A-REAL-KEY-JUST-DEMO-CONTENT-FOR-KUBERNETES-EL
    NOT-A-REAL-KEY-JUST-DEMO-CONTENT-FOR-KUBERNETES-EL
    NOT-A-REAL-KEY-JUST-DEMO-CONTENT-FOR-KUBERNETES-EL
    -----END OPENSSH PRIVATE KEY-----
  db-connection: "postgres://demo:demo@db-headless.kubernetes-el-demo.svc:5432/demo?sslmode=disable"
